### ISSUE TITLE
Roadmap v2

### ISSUE THREAD

**Issue by hannaeko** [AIR-EISTI/hades#1]
- [x] Change from pty.js to node-pty (build fail on node 10)
- [x] Rebuild front with last angular version
- [x] Improve client design
- [x] Remove jsonfile from dependencies list
- [x] Remove ejs, templates and static files from api server
- [x] Use xtermjs client side for terminal emulation
- [x] Switch from socket.io to express-ws and native web socket client-side
- [x] Reimplement v1 features
  - Client
    - [x] List games
    - [x] List servers
    - [x] Launch game
    - [x] Live console
    - [x] Stop server
    - [x] Server list live reload
  - Server
    - [x] List game configs
    - [x] List servers
    - [x] Get server info
    - [x] Stop server
    - [x] Config hot reload
