### ISSUE TITLE
Roadmap v2.1

### ISSUE THREAD

**Issue by hannaeko** [AIR-EISTI/hades#3]
- [ ] Laggy connection ?
- [ ] Better font for front end
- [x] Config schema check (ajv)
- [x] Add perf graph
  - [x] App perf api for server (websocket)
  - [x] Graph component client side
    - [x] Basic graph view
    - [x] Dynamic update
    - [x] Grid background  / Axis ?
    - [x] History info on hover (vertical cursor + label)
- [x] Responsive terminal size
  - [ ] ~Min width~
  - [x] Terminal fit
  - [x] pty resize
  - [x] Multi client support (smaller terminal wins)
